### PR TITLE
Add psgix.informational callback

### PR DESCRIPTION
**Pull request by robrwo**
This adds an informational callback as per Starlet or Gazelle
servers.

It also changes the "100 Continue" handler to use the callback
method code.

### CODE REVIEW

**Comment by miyagawa** [comment]
This looks great! Is it possible to write a unit test for this?

**Comment by robrwo** [comment]
> This looks great! Is it possible to write a unit test for this?

I tried writing one but wasn't sure how to get the raw HTTP result without modifying Plack::Test. (I was hoping there was a HTTP 100 test I could borrow from.)

Do you have any ideas how this could be done?

**Comment by robrwo** [comment]
> This looks great! Is it possible to write a unit test for this?

Done.

**Comment by robrwo** [comment]
Any plans to release a new version with this change soon?

**Pull request merged**
